name: Build and Test

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build_test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: ['14', '15', '16']

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install dependencies and build
        run: |
          npm ci
          npm run build --if-present
          npm test
          if [ $? -ne 0 ]; then
            echo "npm test failed"
            exit 1
          fi
